### ISSUE TITLE
Using with Ruby

### ISSUE THREAD

**Issue by MtnBiker** [WaKeMaTTa/geo_names#2]
How would this be used in a Ruby script. I assume the example works, but how do you pass the password?

**Comment by WaKeMaTTa** [comment]
Password?, you mean the `username`?

**Comment by MtnBiker** [comment]
You're right. I mean the username.

**Comment by WaKeMaTTa** [comment]
Here you have the instructions: [how to configure?](https://github.com/WaKeMaTTa/geo_names#configuration)
